name: Build

on: [push, pull_request]

env:
  NPM_CONFIG_CACHE: /root/.cache/npm
  CYPRESS_CACHE_FOLDER: /root/.cache/cypress

jobs:
  prepare-versions:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: set-matrix
        name: Prepare
        run: echo "matrix=$(node -p "JSON.stringify(require('./package.json').peerDependencies['cypress'].split(' || '))")" >> $GITHUB_OUTPUT
      - run: npm -v

  test:
    needs: prepare-versions
    runs-on: ubuntu-20.04
    container:
      image: cypress/base:18.16.0
    strategy:
      matrix:
        cypress-version: ${{fromJson(needs.prepare-versions.outputs.matrix)}}
    steps:
      - name: Update certificates
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: ${{ env.NPM_CONFIG_CACHE }}
          key: npm-linux@${{ matrix.cypress-version }}
      - name: Cache Cypress binaries
        uses: actions/cache@v3
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: cypress-linux@${{ matrix.cypress-version }}
      - name: Change owner
        run: "chown root: ."
      - name: Dependencies
        env:
          CYPRESS_INSTALL_BINARY: "0"
        run: |
          npm install --force && \
          npm install --no-save cypress@${{ matrix.cypress-version }} && \
          env -u CYPRESS_INSTALL_BINARY npx cypress install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Version
        run: npx cypress --version

  windows:
    runs-on: windows-latest
    env:
      NPM_CONFIG_CACHE: ${{ github.workspace }}/.npm
      CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: .npm
          key: npm-windows
      - name: Cache Cypress binaries
        uses: actions/cache@v3
        with:
          path: .cypress
          key: cypress-windows
      - name: Dependencies
        shell: bash
        run: npm install
      - name: Build
        run: npm run build
      # https://github.com/webpack/webpack/issues/12759
      - name: Remove Webpack test
        run: rm features/loaders/webpack.feature
      - name: Test
        run: npm run test:integration
